allan_node:
  ros__parameters:
     topic: # /your/topic 
     bag_path: # path/to/bag.db3
     msg_type: # use 'ros' for sensor_msgs::msg::Imu, use 'px4' for px4_msgs::msg::VehicleImuStatus
     publish_rate: # your imu publish rate (hz) 
     sample_rate: # rate to sample data from bag. Higher sample rates take longer to compute 